app/administrator/models.py
from app.database import BaseModel
from app.extensions import db, admin, login_manager
from flask_login import UserMixin
from app.admin_panel import MyModelView


@login_manager.user_loader
def load_user(administrator_id):
    return Administrator.query.get(int(administrator_id))


class Administrator(BaseModel, UserMixin):
    username = db.Column(db.String(30), unique=True, nullable=True)
    email = db.Column(db.String(60), unique=True, nullable=False)
    phone = db.Column(db.String(11), unique=True, nullable=True)
    password = db.Column(db.String(60), nullable=False)
    articles = db.relationship('Article', backref='author', lazy=True)

    def __repr__(self):
        return f'{self.__class__.__name__} ({self.id}, {self.username})'


admin.add_view(MyModelView(Administrator, db.session))

app/articles/models.py
from app.database import BaseModel
from app.extensions import db, admin
from app.admin_panel import MyModelView
from flask_login import current_user
import datetime


class Article(BaseModel):
    title = db.Column(db.String(120), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.datetime.now)
    content = db.Column(db.Text, nullable=False)
    administrator_id = db.Column(db.Integer, db.ForeignKey('administrator.id'), nullable=True,
                                 default=lambda: current_user.id if current_user.is_authenticated else None)

    def __repr__(self):
        return f'{self.__class__.__name__}({self.id}, {self.title[:30]}, {self.date})'


admin.add_view(MyModelView(Article, db.session))

app/administrator/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField


class AdministratorLoginForm(FlaskForm):
    email = EmailField('Email')
    password = StringField('Password')

app/__init__.py
from flask import Flask
import app.exceptions as app_exception
from app.extensions import db, migrate, admin, login_manager, bcrypt
from app.admin_panel import MyAdminIndexView
from app.routes import register_blueprint


def register_error_handlers(app):
    app.register_error_handler(404, app_exception.page_not_found)
    app.register_error_handler(500, app_exception.server_error)


app = Flask(__name__)
register_blueprint(app)
register_error_handlers(app)
app.config.from_object('config.DevConfig')
db.init_app(app)

from app.administrator.models import Administrator
from app.articles.models import Article
from app.administrator import routes

migrate.init_app(app, db)
login_manager.init_app(app)
admin.init_app(app, index_view=MyAdminIndexView())
bcrypt.init_app(app)

app/administrator/routes.py
from app import app
from flask import render_template, redirect, flash
from app.administrator.models import Administrator
from app.administrator.forms import AdministratorLoginForm
from app.extensions import bcrypt
from flask_login import login_user, current_user, logout_user


@app.route('/admin/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect('/admin')

    form = AdministratorLoginForm()
    if form.validate_on_submit():
        administrator = Administrator.query.filter_by(email=form.email.data).first()
        if administrator and bcrypt.check_password_hash(administrator.password, form.password.data):
            login_user(administrator)
            flash('you logged in successfully', 'success')
            return redirect('/admin')
        else:
            flash('email or password is wrong', 'danger')
    return render_template('administrator/login.html', form=form)


@app.route('/admin/logout')
def logout():
    logout_user()
    return redirect('/')

app/articles/routes.py
from flask import Blueprint, render_template
from app.articles.models import Article
blueprint = Blueprint('post', __name__)


@blueprint.route('/article/<int:article_id>')
def detail(article_id):
    article = Article.query.get_or_404(article_id)
    return render_template('front/detail.html', article=article)

app/home/routes.py
from flask import Blueprint, render_template, request
from app.articles.models import Article

blueprint = Blueprint('home', __name__)


@blueprint.route('/')
def home():
    articles = Article.query.all()
    page = request.args.get('page', 1, type=int)
    per_page = 1
    start = (page - 1) * per_page
    end = start + per_page
    total_pages = (len(articles) + per_page)
    items_on_page = articles[start:end]
    return render_template('front/home.html', articles=items_on_page, total_pages=total_pages, page=page)

app/routes.py
from app.home.routes import blueprint as home_blueprint
from app.articles.routes import blueprint as post_blueprint


def register_blueprint(app):
    app.register_blueprint(home_blueprint)
    app.register_blueprint(post_blueprint)

app/templates/administrator/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    {% include 'administrator/includes/messages.html' %}
    {% block content %}{% endblock %}
</body>
</html>

app/templates/administrator/includes/form_errors.html
{% if form.code and form.code.errors %}
    {% for error in form.code.errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endfor %}
{% endif %}

{% if form.email and form.email.errors %}
    {% for error in form.email.errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endfor %}
{% endif %}

{% if form.verify and form.verify.errors %}
    {% for error in form.verify.errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endfor %}
{% endif %}

app/templates/administrator/includes/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for cat,msg in messages %}
            <p class="alert alert-{{cat}}">{{ msg }}</p>   
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/administrator/login.html
{% extends 'administrator/base.html' %}

{% block content %}
    <!-- no additional media querie or css is required -->
    <div class="container">
        <div class="row justify-content-center align-items-center" style="height:100vh">
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        {% include 'administrator/includes/form_errors.html' %}
                        <form action="" method="POST">
                            {{ form.csrf_token }}
                            <div class="form-group">
                                {{ form.email(class='form-control', placeholder='email') }}
                            </div>
                            <div class="form-group">
                                {{ form.password(class='form-control', placeholder='password') }}
                            </div>
                            <input type="submit" class="btn btn-primary" value="Login">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/front/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    {% include 'front/includes/navbar.html' %}
    <div class="jumbotron">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/front/detail.html
{% extends 'front/base.html' %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
    <h3> {{ article.title }} </h3>
    <small>{{ article.author.username }} - {{ article.date.strftime('%Y-%m-%d') }}</small>
    <hr>
    <p>{{ article.content }}</p>
{% endblock %}

app/templates/front/home.html
{% extends 'front/base.html' %}

{% block title %}
    Blog
{% endblock %}

{% block content %}
    <h3> home </h3>

    <div class="card">
        {% for article in articles %}
            <a href="{{ url_for('post.detail',article_id=article.id) }}" class="card-body">{{ article.title }}</a>
        {% endfor %}
    </div>
    {% if page > 1 %}
        <a href="{{ url_for('home.home',page=page-1) }}">Previous</a>
    {% endif %}
    <span>Page {{ page }} of {{ total_pages }}</span>
    {% if page < total_pages %}
        <a href="{{ url_for('home.home',page=page+1) }}">Next</a>
    {% endif %}
{% endblock %}

app/templates/front/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('home.home') }}">home</a>
</nav>